[project]
name = "generativeai-course"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "anthropic>=0.63.0",
    "dotenv>=0.9.9",
    "ipykernel>=6.30.1",
    "wikipedia>=1.4.0",
]
